name: Full Build and Deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '!src/BoneLog.Blazor/wwwroot/**'
      - '!src/BoneLog.Blazor/Automations/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Full Build and Deploy

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish Blazor Project
      run: dotnet publish src/BoneLog.Blazor/BoneLog.Blazor.csproj -c Release -o release --nologo

    - name: Change base href in index.html
      run: sed -i 's|<base href="/" />|<base href="/BoneLog/" />|g' release/wwwroot/index.html

    - name: Change base href in 404.html
      run: sed -i 's|<base href="/" />|<base href="/BoneLog/" />|g' release/wwwroot/404.html

    - name: Add .nojekyll
      run: touch release/wwwroot/.nojekyll

    - name: Deploy full build output
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: release/wwwroot
